networks:
  my-network:

services:
  mynextapp:
    container_name: mynextappcontainer
    build: ./
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./my-next-app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - my-network
